export const plugins = [
  "accordion",
  "advlist",
  "anchor",
  "autolink",
  "autoresize",
  "autosave",
  "charmap",
  "code",
  "codesample",
  "directionality",
  "emoticons",
  "fullscreen",
  "help",
  "image",
  "importcss",
  "insertdatetime",
  "link",
  "lists",
  "media",
  "nonbreaking",
  "pagebreak",
  "preview",
  "quickbars",
  "save",
  "searchreplace",
  "table",
  "visualblocks",
  "visualchars",
  "wordcount",
]

export const toolbar = [
  "undo redo blocks bold italic underline strikethrough  alignleft aligncenter alignright alignjustify bullist numlist forecolor backcolor  image table  outdent indent  link media code blockquote removeformat codesample hr preview anchor pagebreak insertdatetime fullscreen",
]
